/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./components/AboutMe.vue')['default']
    AuthorName: typeof import('./components/AuthorName.vue')['default']
    DeveloperName: typeof import('./components/DeveloperName.vue')['default']
    MainSection: typeof import('./components/MainSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollButton: typeof import('./components/ScrollButton.vue')['default']
    Skill: typeof import('./components/Skill.vue')['default']
    WorkInfo: typeof import('./components/WorkInfo.vue')['default']
  }
}
